[package]
name = "vps_bench"
version = "0.1.0"
authors = ["dev <dev@qiyutech.tech>"]
edition = "2018"

[[bin]]
name = "vps_bench"
path = "src/main.rs"

[dependencies]
structopt = { version = "0.3" }

rand = { version = "0.8", features = ["small_rng", "getrandom"] }
