[package]
name = "vps_bench"
version = "0.0.1-pre"
authors = ["dev <dev@qiyutech.tech>"]
edition = "2018"
license-file = "LICENSE"
homepage = "https://vps.qiyutech.tech/"

[[bin]]
name = "vps_bench"
path = "src/main.rs"

[dependencies]
structopt = { version = "0.3" }

rand = { version = "0.8", features = ["small_rng", "getrandom"] }
