name: Cross

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: rust version
        run: rustc --version

      - name: install cross
        run: cargo install cross

      - name: install ssl on linux
        if: strategy.os == 'ubuntu-20.04'
        run: apt install -y gcc pkg-config libssl-dev

      - name: cross build
        run: cross build --verbose

